### ISSUE TITLE
GAN loss problem

### ISSUE THREAD

**Issue by XsherryR** [Zj-BinXia/KDSR#1]
Thanks for your wonderful work!
I have some questions about the GAN loss:
In your paper appendix, you seem to use the hinge GAN loss. However, in your train_kdsrgan_x4ST.yml, you use the vanilla gan type and the weight of GAN loss is 1, which is 0.1 in your paper. Could  you tell me what I'm getting wrong?

**Comment by Zj-BinXia** [comment]
Thanks for your interest! You can follow my code setting, and the weight of GAN loss is 1.

**Comment by XsherryR** [comment]
Thanks for your reply!  I'm trying to follow your GAN loss setting to train my own network, but the GAN loss you use is different in the paper and train_kdsrgan_x4ST. yml, so I want to know which GAN loss is exactly you use?  and which can achieve a better performance？ Thanks for your advice!

**Comment by Zj-BinXia** [comment]
I use the GAN loss settings of train_kdsrgan_x4ST, which are slightly better than the paper GAN settings.
