### ISSUE TITLE
KD loss coefficient

### ISSUE THREAD

**Issue by juniorprincewang** [Zj-BinXia/KDSR#2]
Shouldn't the KD loss coefficient $\lambda_{kd}$ or $\lambda_{kl}$  be set 0.15 instead of 1 in [train_kdsrgan_x4ST.yml]( https://github.com/Zj-BinXia/KDSR/blob/master/KDSR-GAN/options/train_kdsrgan_x4ST.yml#L192C19-L192C19)?
And does the temperature need to be corrected?
Thanks.

**Comment by Zj-BinXia** [comment]
The settings of this file is right. Temperature is set to 0.15 and weight is set to 1.
